{
    "krmaxwell": "Now if I can just get thug to build and install reliably...\n. Fixed in 7f75d5a2d730a68d6c1aa62235e01bbdf53e3daa\n. Fixed in d4db164c7fed130b203f46e6afdff82e0758c10b\n. Fixed in 949fa6620199ec1f1e8280faac8ec8db182a9180\n. Nictasoft does not list full URLs, so we can't use them. :disappointed: \n. Heard from somebody that they patched in VxCage support. Now to find who it was so I can get the code...\n. Good catch, thought I had closed this. Thanks!\n. Fixed in 8b5bfee7ef4a51e99848dafb26c9fd309ebd7996\n. So let's see, what do we need in the table, assuming somebody isn't using VxCage?\n- timestamp\n- URL\n- hashes (MD5/SHA1/SHA256/ssdeep)\n- headers (text blob?)\nMaybe we should just use Malwarehouse after all.\n. Since we support VxCage, I'm disinclined to create yet another malware database. Instead, I'd rather make sure that we log any additional metadata into VxCage (or Malwarehouse from @sroberts if he ever gets that next gen stuff into a usable state). But I'd definitely like to store this stuff in the pickled objects for non-DB users, or maybe in a JSON flat-file DB.\n. At this point, since Maltrieve supports VxCage, it's not a major issue here. I tend agree that there's probably room for another malware DB project, but I'm leaning towards just storing the stuff we need to keep in a JSON file (pickle feels like an ugly and inferior solution).\n. MongoDB is something useful to have (and I like working with it), but Maltrieve will never require it. I know of too many folks running it in very small capacity environments (e.g. on a Raspberry Pi, which is totally awesome and also fantastic.\nMight add to a future milestone, though.\n. We'll be using VIPER Soon(tm).\nhttps://github.com/botherder/viper\n. Since we have VIPER now, closing this. \n. Looking for some help.\n. This is resolved now that we've moved to grequests.\n. Hm, that's interesting. It is definitely trickier than the other sources, but I have a few tricks up my sleeve from a related issue (grabbing IOCs in unstructured blog posts like Dynamoo et al.), so I'll mull on this. \nPull requests won't be unappreciated though!\n. Thinking more about this: how do you suggest handling the archive passwords given that they are not public per se (TLP:AMBER, as it were)?\n. Closing this unless we can figure out how to handle the archive password issue.\n. Because it's a scheme...\n. Thanks for the request. Can you elaborate a little on what you mean?\n. Looks like this is covered by issue #10 and will be addressed soon :)\n. Also see issue #20 :)\n. Thanks for the report, I will take a look.\n. I'm looking at it and still debugging. Progress but Python is not catching the exception where I expected it to.\n. Improved logging from pull request #20 should help. This is not forgotten!\n. Thanks for the report, I will take a look!\n. This should be the same as #21 and now resolved. Please let me know if it recurs! :relieved: \n. Issue #22 should help with resolving this (because we need to log more info to see what's happening).\nRegardless, needs better exception handling!\n. Looks cool and addresses issue #7. Going to pull into a new branch for testing.\n. Good catch, thanks!\n. Something's definitely up with the user's lxml install - as far as I can tell, the problem is a compile issue with that build. See http://bubblenet.be/blog/z3c.recipe.staticlxml-0.9-fixes-undefined-symbol-clock_gettime or similar. You might need to see if you can get an updated version of lxml.\nI don't currently have a spare Raspberry Pi for testing but I will try to free one up soon.\n. Confirmed that it's resolved in latest versions of python-lxml.\n. It looks like one of my try/except clauses needs a fix, thanks. And I'll look into the Malware Patrol URL!\n. I just released beta-2b that should fix this problem. Can you run again and let me know if it still recurs? Thanks for your report!\n. Thanks, but not quite ready for beta3 release. Need to complete #10 first, probably later this week.\n. No worries!\nOn Tue, Oct 22, 2013 at 2:13 PM, hevnsnt notifications@github.com wrote:\n\nyeah, I'm sorry I clicked the wrong button -- was intending to fork it and\nwork on it myself. =)\nSorry!\nOn Tue, Oct 22, 2013 at 2:12 PM, Kyle Maxwell notifications@github.comwrote:\n\nThanks, but not quite ready for beta3 release. Need to complete #10<\nhttps://github.com/technoskald/maltrieve/issues/10>first, probably later\nthis week.\n\u2014\nReply to this email directly or view it on GitHub<\nhttps://github.com/technoskald/maltrieve/pull/29#issuecomment-26832526>\n.\n\n\u2014\nReply to this email directly or view it on GitHubhttps://github.com/technoskald/maltrieve/pull/29#issuecomment-26832644\n.\n\n\nKyle Maxwell [krmaxwell@gmail.com]\nTwitter: @kylemaxwell\n. :+1: \n. Will be interesting to compare to mine! \n. That was in fact the inspiration :D\n. This is in as of v0.6.\n. I will later port to Python and merge directly into the main code. But for now, this is great, thank you!\n. urlopen no longer in use, replaced with requests and better error handling also added\n. Ok I will try again to reproduce\n On Jun 22, 2014 4:48 PM, \"vito01\" notifications@github.com wrote:\n\nI'm getting the same error with the most recent version\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/technoskald/maltrieve/issues/37#issuecomment-46794048\n.\n. I pulled this into another branch (packaging) so I can get familiar with it and ensure I know how to make the other requisite changes. Then I'll merge your PR :)\n\nAnd thanks :exclamation: \n. Might be useful but it doesn't really list other sources, just has the evil bits available itself.\n. Not going to implement. It doesn't fit the proper use cases.\n. Reviewed and added #50 based on this.\n. https://github.com/botherder/viper\n. This will be the \"real\" implementation of #10 .\n. Thanks!\n. Ctrl-C should work - can you include a console session where it does not for you so I can figure out why?\nAlso, by default Maltrieve uses the system logging facility. You'd prefer something like maltrieve.log in the current working dir?\n. Yes - looking to port this into the core script and allow for more flexibility. Any thoughts on what's useful / not useful to you?\n. @kevthehermit is this something you think would actually be useful?\n. :+1: \n. Try running as python maltrieve.py [options go here] and let me know how that goes.\n. Oh and you'll need to do pip install requests or similar.\n. Can you paste the exact command line you ran? This looks to me like it's interpreting as bash or similar rather than Python, so try the python maltrieve.py method rather than ./maltrieve.py and let me know.\n. DERP I just saw the line 171 error @KDPryor included. :blush: going to check that out now\n. @mlawsonis Try pulling from the beta3a branch. There's still one remaining error (not the one listed above) but this stuff is fixed.\n. Duplicate of #46 (but thanks for the report!!)\n. Traceback (most recent call last):\n  File \"./maltrieve.py\", line 297, in <module>\n    main()\n  File \"./maltrieve.py\", line 242, in main\n    get_xml_list('http://www.malwaredomainlist.com/hostslist/mdl.xml', malq)\n  File \"./maltrieve.py\", line 118, in get_xml_list\n    tree = ET.parse(r.text)\n  File \"/usr/lib/python2.7/xml/etree/ElementTree.py\", line 1182, in parse\n    tree.parse(source, parser)\n  File \"/usr/lib/python2.7/xml/etree/ElementTree.py\", line 647, in parse\n    source = open(source, \"rb\")\nIOError: [Errno 36] File name too long:\nFollowed by the contents of the page.\n. lxml / etree no longer used so this no longer applies\n. Turns out these are \"just\" control panels.\n. yeah stuff is very fluid right now. I need to add that to the listed requirements.\n. Thanks! If you don't mind @mlawsonis I'd happily include a text version in the actual tool as well. Feel free to submit a PR.\n. btw this should be documented properly as of 0f150934b2da4901e7036fb9872257d10e931079 (plus in the README).\n. Good idea!\n. Already implemented by @kevthehermit actually.\n. Many thanks! :clap: \n. Dunno, will check.\n. Pretty sure this will happen if the directory doesn't already exist. Should we create it or just document that it should exist?\n. So it turns out the code to create it is there. Not sure yet what's causing this to break.\n. Still reproed.\n. I think #120 fixed this. Pending a few days of uninterrupted functioning before I have enough confidence to close the issue, though.\n. NOPE!\n. There's a tentative fix in the dev branch now. Feel free to try it if you're brave!\n. This looks like one host sends data at least every 60 seconds, but not much. So the overall download speed for that sample is very slow. I will add an enhancement to track download time per sample to the backlog, but it won't be in this release (v0.7).\n. :troll:\n. The thing is that the actual malware sites sometimes change their\nresponse based on the user-agent. (This is probably a good research\ntopic on its own.)\nI think it could make sense to specify maltrieve to the listing sites,\nthough.\n. FWIW you can always set your User-Agent in the config file to Maltrieve if you want, @sroberts \n. Ah, that's an interesting use case! I'd really like to specify a \"white list\" of types I care most about too - only save PE32s or PDFs or whatever. \n. wrong module, that's all\n. Closing this because we're going to reattempt a different way.\n. Whoa, this looks pretty significant, thanks!\n. That's fixed in later revisions. Try updating Maltrieve to the latest version and you should be good to go.\n. This is definitely buggy old code that's been replaced. That file (malutil.py) doesn't even exist in the current code. Download the newest version either here or from the git repo (git clone git@github.com:technoskald/maltrieve.git from a fresh directory) and try again.\n. now we're onto something interesting! I've not seen this before,  will dig into it.\n. I've been unable to reproduce this. Does this still happen for you?\n. Fixed by #93 and #91 \n. Do you have any repro steps? Try as I might, I can't make this happen.\n. Sounds good. \n. Can one of you who's experienced the issue test the rlimit branch? It implements the fix suggested by @alienone with a limit of 2048 descriptors as @dray0n is using.\n. This is so odd because the Python context manager (with) should close the file when exiting that block. It makes me wonder if grequests is holding something open.\n. :+1: \n. http://malwareurls.joxeankoret.com/normal.txt is already in the list (at the end). If you look at the \"Files changed\" tab, you'll see it here.\n. No worries, I was halfway thru processing the PR until I realized it!\n. Going to test this tonight. Dunno how I missed it - I sincerely apologize.\n. @sroberts I just didn't want to out you as the user in question, but now I will! \nI am interested in developing this idea further, although YARA support could be a significant chunk to bite off.\n. I look forward to pull requests. :trollface: \n. We could implement a hash filter (whitelist), but I don't think Maltrieve should support YARA directly. You can already accomplish that by integrating Maltrieve with some other analysis tool, like Viper or CRITs.\n. Can you paste the output of pip freeze?\n. Is this still an issue? I suspect you have the wrong module for magic.\n. Yup, definitely the wrong module for magic. You want python-magic (virtual environments will help a lot with this BTW).\n. This is a duplicate of #58 \n. This is the perfect thing for somebody who wants to write some docs without having to dodge code...\n. Feel free, I haven't quite gotten to it yet and anything that shortens time to v0.7 is good :grinning: \n. Fixed in dbe8812\n. @Sh4d0wS4int What would you like to see it do? To date, we've tried to keep Maltrieve focused as a crawler rather than analysis per se, but I'm certainly open to hearing new ideas!\n. Yes, I think this function is best served with an add-on script rather than in the core functionality. I'll see if I can't find a good tool to recommend in the docs here.\n. Thanks! I see it's up at http://minotauranalysis.com/ but apparently the \"recent samples\" function isn't quite ready to go yet. The \"recent URLs\" tab seems kind of sparse right now, probably because they're still getting things back up. I will make a note to check in on that site at the end of the week.\n. Just FYI I have been checking them once or twice a week to see when the feed is ready. Have not lost sight of it!\n. So while the Recent Samples page isn't live, the front page has a Recent URLs tab. Storing the current list here for comparison later to see if it's actually getting updated. If so, we can just parse that and add it back to the rotation\nURL Minotaur ID VT Score    SHA1 Hash\nhttp://www.download-servers.com/vuupc/dl.php?fn=_vof1   2649    4/57    0f68ff446c9c3006f3bc1ee6d8ea42b9d11eb217\nhttp://www.download-servers.com/vuupc/dl.php?fn=_asf1   2649    4/57    0f68ff446c9c3006f3bc1ee6d8ea42b9d11eb217\nhttp://trustfile8.ru/files/1618352/.exe 2647    18/57   9c075bd5d27e71deb39792f58a46570ccc4b56bc\nhttp://trustfile7.ru/files/1506075/tor134231.exe    2646    19/57   f55d79360c8d76abfe0cf0e1b7312866eae9e202\nhttp://trustfile7.ru/files/1463382/tor134231.exe    2645    19/57   2b3509d1097e546c9843f8508f1b78d9438bf502\nhttp://trustfile7.ru/files/1463322/tor134231.exe    2644    19/57   7009771d30146ebab3ade362dbde0afc85823290\nhttp://trustfile7.ru/files/1159422/tor134231.exe    2643    19/57   7051a226f205f34a17acf171f604fad5205358b5\nhttp://trustfile7.ru/files/1062847/maxdownloader.exe    2642    19/57   bd4e55d3188fe35df66ad7623989549d20734264\nhttp://trustfile7.ru/files/1062607/filmtut.exe  2641    18/57   77a510713c2bd74e0f24d38d1e2af5e31b44e37b\nhttp://trustfile7.ru/files/1062590/torr07file.exe   2640    19/56   9ac4c58b2733cdb1392fdd5367133ee942f3b05f\nhttp://trustfile31.ru/files/1185593/t23448.exe  2639    18/57   1a9786465cb8c2cb3ee0c8edb8cc97052afd68e5\nhttp://reduled.info/3232/SystemAdvance_142251841623179.dll  2638    20/57   18d22e72c6e5879217fab6d964698568e91ea77d\nhttp://reduled.info/3232/AppendGeneration_142249546693505.dll   2637    30/57   5e361eb358596a4fd94c00d2aba952581a26777e\nhttp://reddie.net/3131/SystemMaintain_142243637241046.dll   2636    23/57   3ac310c18ce576a283df0e7c61d37911cd60b147\nhttp://giveme7.ru/files/1504998/tor134231.exe   2634    19/57   2dd0a733bf417bf9253b4df4f7c204c056962640\nhttp://giveme7.ru/files/1463417/tor134231.exe   2633    19/57   dbaf8d1f2e3d53cfe867a2719dc2870b2bcec178\nhttp://giveme7.ru/files/1463382/tor134231.exe   2632    19/57   d2aff2badf29698fd519b586cc59f0025b59c226\nhttp://giveme7.ru/files/1463322/tor134231.exe   2631    19/57   a81bfd2a5402774eee6f8492204f8aabc3860d1d\nhttp://giveme7.ru/files/1417528/torrfi7les.exe  2630    19/57   d7a50f0ae456a547ab64dc347ff1a4007871a630\nhttp://giveme7.ru/files/1397858/video.downloadhelper.4.9.24.zip.exe 2629    18/57   68240de02805a86cf35a84c997bd1098c620a1b2\nhttp://giveme7.ru/files/1397744/opera.web.browser.24.0.1558.51.next.zip.exe 2628    16/57   da5fd93a7a79c9db5806292520384da36e129039\nhttp://giveme7.ru/files/1294889/stalker-2--stalker-2-2013.exe   2627    19/57   65457f1f460697c13ca6c851e7f5f9cb2a26429a\nhttp://giveme7.ru/files/1210019/tor134231.exe   2626    19/56   fc10763883d77c6df1664dd9221a6846ecdde900\nhttp://giveme7.ru/files/1209568/tor134231.exe   2625    19/57   60d3d1e6d5e8db0cf3b5f20a73f140e230b8030a\nhttp://giveme7.ru/files/1159422/tor134231.exe   2624    19/56   46d237aab24812795ae9c69f104e41f49db11c66\n. This is indeed better than mine. Will test this evening!\n. I love this Dockerfile and it is much cleaner and better than mine. I made two additional changes.\n1. The Dockerfile is now in ./docker/. From the Docker docs:\n\nIn most cases, it's best to put each Dockerfile in an empty directory, and then add only the files needed for building that Dockerfile to that directory. To further speed up the build, you can exclude files and directories by adding a .dockerignore file to the same directory.\n2. There was a permissions error when running because /home/maltrieve was created and owned by root. An explicit chown -R fixed that.\n. I will investigate this. And a PR to replace whatthehellismyip.com would be welcome too :)\n. @dray0n: I added your suggestion about output (and replaced the site). Can you test and let me know whether this works for you?\n. Sounds like it's working based on comments in #80.\n. Still super slow. Even had to remove it from the README because it caused testing to fail sometimes.\n. Good catch.\n. Merged into dev\n. Two things:\n1. You have an older version and might want to upgrade when you get a chance. No biggie, I don't think.\n2. For your specific question - what does your urls.json file look like?\n. ...maybe...\n. Yeah, code that works across multiple versions is truly terrible. \n. https://docs.python.org/2/howto/pyporting.html\n. Before you delete the file, how big is it?\n. Does a run also save your URLs properly in urls.json?\n. :tada: \n. Can somebody try that?\n. As of v0.6 (just released), you can see the version in setup.py. I'm working on stuff for v0.7 now that will focus on architecture and engineering, at which point it'll be more obvious to users and developers.\n. That's because that's just in v0.6 as mentioned. :) \n. The Python packages are not installing correctly still.\n\npython\nkmaxwell@newton:~/src/maltrieve/docker(docker-update)$ sudo docker run c2eab9eefcb9\n2015/03/19 20:33:06 exec: \"maltrieve\": executable file not found in $PATH\nkmaxwell@newton:~/src/maltrieve/docker(docker-update)$ sudo docker run --rm -it c2eab9eefcb9 /bin/bash\nmaltrieve@e7565b1d556a:~$ maltrieve\nbash: maltrieve: command not found\nmaltrieve@e7565b1d556a:~$ python maltrieve.py\nTraceback (most recent call last):\n  File \"maltrieve.py\", line 23, in <module>\n    import feedparser\nImportError: No module named feedparser\nmaltrieve@e7565b1d556a:~$\n. Of note: this will almost certainly uncover a number of bugs that should also get fixed in v0.7.\n. Using CircleCI mostly because it was ridiculously easy.\n. https://waffle.io/krmaxwell/maltrieve\n. None of these fit Maltrieve (either just addresses or phishing URLs).\n. Thanks for this! Going to look at it in the next day or so.\n. This is merged into dev and will land in master when v0.7 is ready.\n. Fixed in 5253d85394e71b2a4be15c83197523695357c617\n. Derp, I missed some. I should pay more attention.\n. Implementing a globals class.\n. closed by  dfacc63\n. This is merged into dev now.\n. I did a bad bad thing...\n. \n. Also, use pip install ..\nSource: http://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install\n. While this isn't the same as #98, it's a start.\n. alternate: http://contributor-covenant.org/\n. I thought that one of the sources is failing, but I checked and they're all returning 200. And there should indeed be 7 of them (as of right now).\n. --------------- coverage: platform linux2, python 2.7.6-final-0 ----------------\nName        Stmts   Miss  Cover\n-------------------------------\nmaltrieve     250    114    54%\n:tada: \n. Wrong branch, oops.\n. The fact that this code passes tests only means it doesn't break other stuff. I don't have any tests for the upload functions yet.\n. Argh, still getting exception. I suspect it's something with my CRITs instance.\n. OK, just verified my CRITs install has issues. This should be g2g at this point otherwise. Going to merge into dev and we'll catch anything else in later testing.\n. oh, here's the real problem:\nrequests.exceptions.MissingSchema: Invalid URL u'True/api/v1/domains/': No schema supplied. Perhaps you meant http://True/api/v1/domains/?\n. I think you're right, yeah. I looked back at my code after I'd gotten proper :zzz: and focus, and realized my scope errors. Going to shape it up tomorrow to look more like your original code ;)\n. oh and I did have an error with the schema but that was a total brain fart on my part when I assigned the vars\n. Remaining error is just on my CRITs instance and not with Maltrieve.\n. Have you tried this with a virtual environment?\n. Also, thanks for this, I've had a number of private questions about cron so this is going to help a lot of folks. :)\n. Oh that's going to get annoying if it does it after every commit.\n. ```\n$ py.test --cov-report term-missing --cov maltrieve test.py\n=============================================================================================== test session starts ===============================================================================================\nplatform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.7.0\nrootdir: /home/kmaxwell/src/maltrieve, inifile: \nplugins: cov\ncollected 9 items \ntest.py .........\n--------------------------------------------------------------------------------- coverage: platform linux2, python 2.7.6-final-0 ---------------------------------------------------------------------------------\nName        Stmts   Miss  Cover   Missing\n-----------------------------------------\nmaltrieve     324    243    25%   46-126, 129-133, 137-242, 246-261, 266-278, 282-297, 301-344, 355, 357, 378-383, 387, 421, 437-440, 451-502, 506-509\n============================================================================================ 9 passed in 0.97 seconds =============================================================================================\n``\n. -config.init()-upload_*-save_malware()-process_urlquery()-chunker()-main(). I may have a regression error, because I know I wrote tests for most ofconfig.init()andsave_malware()`.\n. This looks fun, actually!\n. No worries, I like where it's headed though.\nOne thing - please open the PR against the dev branch for ease of management. And feel free to ask any questions you might have!\n. Based on discussion in #58\n. repro'ed\n. @eldraco Can you try this hotfix and let me know if it works for you? Thanks for the report!\n. So my inclination is that we should require valid certificates from the list sources (e.g. ZeusTracker) but not from the served samples themselves (because we expect badness there). Thoughts?\n. Based on https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning , it looks like the real fix is to upgrade to v2.7.9 or greater.\n. Orrrr to install the security extras.\n. For me, this is as much about the UX as anything else. All those warnings clutter up the display. Also, assuming that you're using pip install -r requirements.txt then we should be able to do everything via PyPI.\n. So this is an interesting issue and I'm certainly willing to listen to other reasoning and viewpoints. Here's the background behind the original design (which, again, is always subject to review).\n- Downloaded files are dangerous and we want to make sure an analyst never accidentally executes malicious code by accident. \n- The file name may be misleading and not reflect the actual file type. Examining the actual file signature is more accurate for this purpose.\n- We should log the original file name so that it can be reconstructed or analyzed as needed.\nHowever, to re-iterate, if there is a good reason to change this design, or a good way to do it that achieves all the appropriate goals, then we could do that. How would maintaining the original extension help?\n. This looks good!\n. It remembers the URLs previously downloaded and the hashes. If the same file exists at a different URL, it won't know that until it downloads it (but when it does it will see we already have the hash). And it doesn't download the same URL twice.\nSee urls.json and hashes.json for more (although the implementation may change in a future update).\n. For serves that provide a Content-Length HTTP header, we could possibly do this. The caveat of course is that the spec does not require servers to provide this header and so we won't always know a file size until we grab the file. \nIf somebody wants to implement this, I'd like to see it this way:\n- Option in maltrieve.cfg specifying max file size\n- The Body Content Workflow feature of requests can do this with appropriate logic. \n- If no option is specified, then don't restrict file size.\nThis is probably a security issue, to be honest, because a malicious attacker could serve a fake stream to fill up the file system where Maltrieve stores the data. But in that case they probably won't use the Content-Length header and so this wouldn't fix that. So, separately from any code implementation as described above, the documentation should make clear that dumpdir needs to be on a non-system partition to avoid a denial of service.\nI appreciate this question, it's really helpful!\n. If you're just judging from the logs, don't. ;) See #149 for example. Our logging is not good right now.\nSo you've verified in CRITs that the domain is not there but the sample is?\n. So the log indicates that the domain upload is succeeding (unless there's stuff after that from CRITs that we're not seeing in the issue). Have you verified that the user has access to the source, so that you're seeing all the data?\n. What do the details look like if you go the other way, a sample that was just downloaded today?\n. OK I definitely see that the relationship is not being added, so something is up. \n. As long as it's Basic Auth, this is definitely doable. If you need Digest Auth for the proxy, that will take a bit more work.\n. So it looks like we should already support this because we use Requests:\n\nTo use HTTP Basic Auth with your proxy, use the http://user:password@host/ syntax:\n\npython\nproxies = {\n    \"http\": \"http://user:pass@10.10.1.10:3128/\",\n}\nI will note this in the documentation, though!\n. https://devcenter.heroku.com/articles/getting-started-with-python\n. Can you paste the output of pip freeze?\n. and :fearful: I just saw you had pip freeze above. I scrolled past it too quickly, sorry!\nSo I don't see python-magic installed here, but Magic-file-extensions which is a different module. Can you try pip install python-magic and see if that fixes it?\n. Yes, we have Cuckoo integration built-in! Just configure the URL in maltrieve.cfg. It's set to https://127.0.0.1:8090 by default.\nGlad this worked for you :+1: \n. I should lrn2read.\n. Make sure the working directory for the script has maltrieve.cfg in it. You might just need to prepend the script invocation with a cd, something like\ncd /home/maltrieve && ./maltrieve.py\n(if your script and config are in /home/maltrieve).\n. Did this work for you?\n. Thanks for the report! It looks like we need to update the URL and also improve our exception handling. \n. This is still open because of the exception handling, FYI.\n. What version of Maltrieve are you running? And can you paste the output of pip freeze?\n. What KeyError were you getting, and what change did you have to make? \n. Hrm, that's odd since I'm running the code and it's uploading correctly to my CRITs instance. Wonder what's different.\n. Fixed in #165 \n. This was fixed in f969a5f which I've just merged to master. Please update to the newest code - that should do it.\n. Thanks for the reminder!\n. Also see https://remnux.org/docs/containers/run-apps/#maltrieve-malware-samples-downloader-remnuxmaltrieve\n. Hrm, looks like some failed tests, have you looked into those yet?\n. ",
    "mboman": "Check out REMnux Docker images (https://remnux.org/docs/containers/malware-analysis/).\n. I got one done. Will fork & commit Dockerfile when I get home tonight :) \n. See pull request #79 for the Dockerfile.\n. 2016-02-11 21:54:45 140619175761728 Submitted sample a2a24bb9e6c61b438eb207c7ca85c1e5 to CRITs, response was {u'message': u'Must provide an upload type.', u'type': u'Sample', u'return_code': 1}\n. ",
    "sumitb": "Is this issue resolved or is there something left?\n. Issue fixed with #35.\n. ",
    "sroberts": "I'm happy to contribute building this in, but honestly Malwarehouse needs to be leveled up in a big way. Most people don't want 50 samples, they want 50,000. I'm up for building something new to support this, but Malwarehouse is likely not going to be moved a ton. \n. :-1: to pickle. I think a real DB is the way to go just for speed, but I like leaving it in JSON to make it easily integrated with other tools. Might actually be a good time for MongoDB. \n. What says I couldn't run Mongo on a Raspberry Pi? Thats in fact exactly how\nI'd want to run it, with my Rapsberry Pi connected to a USB powered HD.\nOn Mon, Oct 21, 2013 at 12:03 PM, Kyle Maxwell notifications@github.comwrote:\n\nMongoDB is something useful to have (and I like working with it), but\nMaltrieve will never require it. I know of too many folks running it in\nvery small capacity environments (e.g. on a Raspberry Pi, which is totally\nawesome and also fantastic.\nMight add to a future milestone, though.\n\u2014\nReply to this email directly or view it on GitHubhttps://github.com/technoskald/maltrieve/issues/10#issuecomment-26730558\n.\n. Makes sense, Viper is a far better move.\n. Why not just have a configuration where those who know the password can store it?\n. Oh.... you're right. My bad. \n. \ud83d\udc4d like this. I'd consider, if you haven't already, just running https://github.com/pengwynn/flint to help. \n. :sparkles: \n. Easier installation certainly doesn't hurt. :+1: Never set this up though, but if I can help I'm in.\n. I think you just need to run sudo easy_install feedparser from the command line to install the Feedparser module.\n. Yeah that would be super helpful. Same thing with Viper. \n. What more does it need?\n. I guess nothing!\n. I say just create it. \n\nAs the great software developer Drake once said: YOLO. \n. I mean... there's something to be said for having your own user-agent for Maltrieve. It would provide good information for malware providing sites.\n. Not really trolling, I honestly thing it's a legitimate idea. Giving people the chance to change it without digging too far into is a good thing, but by default I think it's valuable insight being lost. Just my 2c.\n. :metal:\n. @technoskald That's exactly what I hacked together, but I think I can do something better. The other idea, though this gets complex, would be to add the ability to monitor for a specific yara rule hitting.\n. Ehh I might be willing to help with that.... now that I'm outed.\n. This to me really feels like scope creep. I understand the temptation, but this seems like a great use case for some kind of secondary tool. Just my 2 cents.\n. Are you really gonna do that? Really?!\n. 100% worth it!\n. ",
    "famthegeek": "Since it grabs the md5 and files from the sources, we should be able to grab things like the name, date discovered etc from the sources as well and store it in a database for later use\n. ",
    "marcomafcorp": "Any update on this, I'm having the same identical issue. Has there been a fix that you haven't posted?\n. Great news please keep me posted on this!\nSent from my iPhone\nOn May 25, 2013, at 11:04 AM, Kyle Maxwell notifications@github.com wrote:\n\nI'm looking at it and still debugging. Progress but Python is not catching the exception where I expected it to.\n\u2014\nReply to this email directly or view it on GitHub.\n. \n",
    "KDPryor": "I'm happy to test anything if you want me to. Just let me know.\n. I already had requests installed. I'll try it again when I get home. \n. ",
    "trietptm": "I receive this error too.\n. I create the directory /tmp/malware manually and it solves the error.\ntechnoskald, you should check if the directory exists and create this directory if it doesn't exit :) .\n. ",
    "IntimacyGel": "I found that the mcbrtext xml feed is down so I guess this needs to get pulled out of the script:\nmcbrtext=get_URL('http://www.malware.com.br/cgi/submit?action=list')\n    for url in mcbrtext.read().splitlines():\n        if re.match('^http', url):\n            push_malware_URL(url,malq)\"\n. Wow man you're quick :+1: \n. ",
    "hevnsnt": "yeah, I'm sorry I clicked the wrong button -- was intending to fork it and\nwork on it myself. =)\nSorry!\nOn Tue, Oct 22, 2013 at 2:12 PM, Kyle Maxwell notifications@github.comwrote:\n\nThanks, but not quite ready for beta3 release. Need to complete #10https://github.com/technoskald/maltrieve/issues/10first, probably later this week.\n\u2014\nReply to this email directly or view it on GitHubhttps://github.com/technoskald/maltrieve/pull/29#issuecomment-26832526\n.\n. \n",
    "unload": "I found your repo earlier today, i think I can help you with packaging. Check out my v3n0m scanner repo for ideas on how you can package using setuptools. It's quite simple, contrary to how it looks on some repos.\n~/git/V3n0M-Scanner$ sudo python setup.py install\nrunning install\nrunning build\nrunning build_py\nrunning install_lib\ncopying build/lib/v3n0m/v3n0m.py -> /usr/lib/python2.7/site-packages/v3n0m\nbyte-compiling /usr/lib/python2.7/site-packages/v3n0m/v3n0m.py to v3n0m.pyc\nrunning install_egg_info\nWriting /usr/lib/python2.7/site-packages/V3n0m-3.4.0-py2.7.egg-info\n. I'll continue to work on it after the merge. And you're welcome!\n. ",
    "vito01": "I'm getting the same error with the most recent version\n. ",
    "zam89": "Maybe you can use CTRL-Z to exit. And also use options -l  to log all activities.\n. Nah. It's ok now. I just run pip uninstall python-magic several time. Then I confirm back by pip freeze. Then I try installing back the package back. Try run the maltrieve and everything works fine. :)\n. Hi,\nI've try your solution and it works perfectly.\nOutput from maltrieve:\n```\n$ python maltrieve.py -v -d pull -l maltrieve.log\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/gevent/threadpool.py\", line 203, in _worker\n    value = func(args, *kwargs)\ngaierror: [Errno -2] Name or service not known\n(, ) failed with gaierror\nCompleted downloads\n```\nOutput from Viper API:\n```\npython api.py\nBottle v0.12.8 server starting up (using WSGIRefServer())...\nListening on http://localhost:8080/\nHit Ctrl-C to quit.\n127.0.0.1 - - [25/Jul/2015 15:37:45] \"POST /file/add HTTP/1.1\" 200 26\n[!] File exists already\n127.0.0.1 - - [25/Jul/2015 15:37:45] \"POST /file/add HTTP/1.1\" 500 41\n[!] File exists already\n127.0.0.1 - - [25/Jul/2015 15:37:46] \"POST /file/add HTTP/1.1\" 500 41\n```\nHope this will help for those that have similar problem.\n+1 nice one @jrespeto \n. ",
    "Sl8v": "Sorry for FP. Can't reproduce this issue today. \n. ",
    "mlawsonis": "This functionality is provided by the maltrievecategorizer.sh. It sorts by type and size. \n. I removed the organize by size.,So I'd like to see that as and option. \nJust a suggestion as I have zero bash skills. I'd like to see it zip each file individually and password protect them. This would make it safer to port samples around without risking accidental infection. \n. did this get resolved? I just did a git today and I'm seeing the same line 171 error. \n. I'll add this to my guide and submit. \nSent from my iPhone\n\nOn Jul 8, 2014, at 5:55 PM, Kyle Maxwell notifications@github.com wrote:\nyeah stuff is very fluid right now. I need to add that to the listed requirements.\n\u2014\nReply to this email directly or view it on GitHub.\n. Any work arounds if running in as a cronjob? \n. I like the idea as a secondary function like submit to cuckoo. \n. Yes, thank you. \n. Can I just comment out the VXVault line as a work around? I removed VX Vault and it's working fine. \n. \n",
    "kevthehermit": "With the new mime type scanning, we could sort in to folders by mime.\n. Yes and more than that im going to write it this weekend :p\n. Done, :) https://github.com/technoskald/maltrieve/pull/71\n. I think its this - \nd = tempfile.mkdtemp(dir=cfg['dumpdir'])\nthis generates this error if the dir doesn't already exist\n2014-09-28 11:14:33 139749181601536 Could not open archive for writing ([Errno 2] No such file or directory: 'archive/tmpIUwxjK'), using default\nshould be easy to put a os.makedirs just before this\n. ",
    "fconcklin": "Ran this with requests installed and have reproduced the same error (have all other listed dependencies as well). Python 2.7.\n. ",
    "rubinatorz": "It seems that the latest pending download is extremely slow... when using wget to get that file manually, it's extremely slow too. Maybe the specific site slows down the whole process?\n. I tried your fix and the first time I ran it, it looked like it solved the problem:\n$ ./maltrieve.py \nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nCompleted downloads\nBut after running it for the 2nd and 3rd time, it seems hanging again...\nRunning it for the 4th time, it looks like it hangs for several times, but after 3 hours it finally completes. Strange, because 3 hours seems quite long for just 43 executables. When looking at the timestamps in the log I see 4 moments with minutes(!) of inactivity:\n\n2015-04-01 11:29:01 -1219635456 \"GET /soft/UploadFile/201501/win7/2015011205.exe HTTP/1.1\" 200 2269518\n2015-04-01 11:35:01 -1219635456 http://hiroba.dqx.jp.sd.sqbzb.com/ hashes to 62505f9257668a74605bfed1e35cc10e\n...\n2015-04-01 11:35:21 -1219635456 \"GET / HTTP/1.1\" 200 None\n2015-04-01 12:39:30 -1219635456 http://dx23.downyouxi.com/wodishijie1.4.2zhongwenban.exe hashes to 05c64c0870a8c8a62bd09ddf41ddf0a2\n....\n2015-04-01 12:44:23 -1219635456 \"GET /shuimiaoflashtzscq.exe HTTP/1.1\" 200 1982464\n2015-04-01 13:28:41 -1219635456 http://jszshb.com/ hashes to 1b9e8f2caa3d6a4df4c117adb5470c9f\n...\n2015-04-01 13:31:50 -1219635456 \"GET /category/ HTTP/1.1\" 500 None\n2015-04-01 13:56:11 -1219635456 http://creative.ad132m.com/ad132m/scripts/direct/direct.html?\n\n. ",
    "adimenia": "I downloaded the new version and im getting these exceptions\nException in thread Thread-5:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 552, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 505, in run\n    self.__target(_self.__args, *_self.__kwargs)\n  File \"/usr/local/bin/maltrieve.py\", line 52, in get_malware\n    mal = get_URL(url)\n  File \"/usr/local/maltrieve/malutil.py\", line 17, in get_URL\n    response.getcode())\nUnboundLocalError: local variable 'response' referenced before assignment\n2014-10-18 11:46:03 -1236354192 urlopen() returned error [Errno 111] Connection refused\n2014-10-18 11:46:03 -1236354192 Fetched URL www.free-ocr.org/FreeScanandOCRtoWord.exe from queue\n2014-10-18 11:46:03 -1236354192 1025 items remaining in queue\nException in thread Thread-3:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 552, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 505, in run\n    self.__target(_self.__args, *_self.__kwargs)\n  File \"/usr/local/bin/maltrieve.py\", line 52, in get_malware\n    mal = get_URL(url)\n  File \"/usr/local/maltrieve/malutil.py\", line 17, in get_URL\n    response.getcode())\nUnboundLocalError: local variable 'response' referenced before assignment\n2014-10-18 11:46:04 -1219568784 urlopen() returned error [Errno 111] Connection refused\n2014-10-18 11:46:04 -1219568784 Fetched URL baixaanexo.cloudapp.net/Org-Boletim-de-Ocorrencia_gerado_online_de.zip from queue\n2014-10-18 11:46:04 -1219568784 1024 items remaining in queue\nException in thread Thread-1:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 552, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 505, in run\n    self.__target(_self.__args, *_self.__kwargs)\n  File \"/usr/local/bin/maltrieve.py\", line 52, in get_malware\n    mal = get_URL(url)\n  File \"/usr/local/maltrieve/malutil.py\", line 17, in get_URL\n    response.getcode())\nUnboundLocalError: local variable 'response' referenced before assignment\n2014-10-18 11:46:05 -1244746896 urlopen() returned error [Errno 111] Connection refused\n2014-10-18 11:46:05 -1244746896 Fetched URL ww.yuchengdjc.com/s.exe?_upd=G30769_s_0529.exe from queue\n2014-10-18 11:46:05 -1244746896 1023 items remaining in queue\nException in thread Thread-4:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 552, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 505, in run\n    self.__target(_self.__args, *_self.__kwargs)\n  File \"/usr/local/bin/maltrieve.py\", line 52, in get_malware\n    mal = get_URL(url)\n  File \"/usr/local/maltrieve/malutil.py\", line 17, in get_URL\n    response.getcode())\nUnboundLocalError: local variable 'response' referenced before assignment\n2014-10-18 11:46:24 -1227961488 urlopen() returned error [Errno 111] Connection refused\n2014-10-18 11:46:24 -1227961488 Fetched URL events.unr.edu/event/nbc_baylor_vs_west_virginia_live from queue\n2014-10-18 11:46:24 -1227961488 1022 items remaining in queue\nException in thread Thread-2:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 552, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 505, in run\n    self.__target(_self.__args, *_self.__kwargs)\n  File \"/usr/local/bin/maltrieve.py\", line 52, in get_malware\n    mal = get_URL(url)\n  File \"/usr/local/maltrieve/malutil.py\", line 17, in get_URL\n    response.getcode())\nUnboundLocalError: local variable 'response' referenced before assignment\neverytime on the same place \n. thanks...i downloaded the new code. (i also seemed to miss some dependencies so i downloaded them too.) now this is what i get after download is finished\nCompleted downloads\nTraceback (most recent call last):\n  File \"./maltrieve.py\", line 336, in \n    main()\n  File \"./maltrieve.py\", line 327, in main\n    json.dump(past_urls, urlfile)\n  File \"/usr/lib/python2.7/json/init.py\", line 181, in dump\n    for chunk in iterable:\n  File \"/usr/lib/python2.7/json/encoder.py\", line 436, in _iterencode\n    o = _default(o)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 178, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nissues with jason?\n. I will check asap and let you know\n\u05d1\u05ea\u05d0\u05e8\u05d9\u05da 14 \u05d1\u05e0\u05d5\u05d1 2014 23:01, \"Kyle Maxwell\" notifications@github.com \u05db\u05ea\u05d1:\n\nI've been unable to reproduce this. Does this still happen for you?\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/technoskald/maltrieve/issues/65#issuecomment-63128334\n.\n. \n",
    "GelosSnake": "I did try to reproduce and failed, I think we should close it and than maybe later open if it returns. \n. Error just came back:\nTraceback (most recent call last):\n  File \"maltrieve.py\", line 336, in \n  File \"maltrieve.py\", line 326, in main\nIOError: [Errno 24] Too many open files: 'urls.json'\n. cheers\n. +1 \n. Sorry I'm a moron lol!\n. Great tool by the way thank you for this!\n. I started to work on categorizer by yara rules before sending to viper (add auto tags). \nMaybe add an option/module for yara scan and than put some kind of \"monitor\" behavior? \n(-y ) will scan from index of yara rules\n-mH (monitor for list of hashes)\n-mY (monitor from list of yara rules)\njust an idea. \n. ",
    "webstergd": "I also just got this error today. This was from a fresh install and occurred on the first and second attempt to execute the program. First quit at ~644 files and the second quit around 1300ish. The third try seemed to work fine. I looked through the code and could not find anything that looked like it could cause this error. \n. Hey do you still need someone to document how to do this? If so i will knock it out for you real fast.\n. Of course and please let me know if you need anything (like my logs) or would like any changes made. I am happy to do so. \n. Hey Kyle. The URL parsing works well on my end. So I am pretty sure that is not the issue. \nI looked at your changes and I think the issues is with your try except blocks. In both sample and domain you are calling \"domain_response\" and \"sample_response\" outside the try block. If something breaks in the post then it is possible that those variables will not be assigned . \nIf we switch it to something basic we should be good to go. This is for both the sample and domain. i.e.:\n        except:\n            logging.info(\"Exception caught from CRITs when submitting domain\")\n. sounds good. Please just let me know if I can do anything to help. \n. This will work in your basic set up and in your basic VM environments. I haven't tried it in any of the fancier virtual environment setups like Docker. If you want I can do another pull request at a later data on how to do that.\n. I do not think Ubuntu LTE has upgraded to that version yet on the standard\ninstall. I think it is a nice to have with the source list. It really\nshouldn't matter when downloading the samples as it is already malicious.\nPeople should also be using a Proxy.\nOn Tue, May 26, 2015 at 5:27 PM, Kyle Maxwell notifications@github.com\nwrote:\n\nOrrrr to install the security extras\nhttp://stackoverflow.com/a/29202163/1569808.\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/krmaxwell/maltrieve/issues/143#issuecomment-105567737\n.\n. fully agree. That warning is an annoying one for sure.\n\nOn Tue, May 26, 2015 at 9:36 PM, Kyle Maxwell notifications@github.com\nwrote:\n\nFor me, this is as much about the UX as anything else. All those warnings\nclutter up the display. Also, assuming that you're using pip install -r\nrequirements.txt then we should be able to do everything via PyPI.\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/krmaxwell/maltrieve/issues/143#issuecomment-105643486\n.\n. Hey Mark,\n\nSorry it is late and I am having trouble understanding your problem. Are\nyou saying that domains are not added properly but that samples are?\nOn Sun, Apr 5, 2015 at 2:23 AM, markmaunu notifications@github.com wrote:\n\nHello -\nBoth domain and sample submission were successfully submitting and that\nrelationship added in the webstergd fork, but moving to the latest master\nsamples but not domains now succeed. The first part of domain submission is\nthe failure then it succeeds submitting and adding to CRITs.\nEx log below (obfuscated URL for safety and took out my legit MYAPIKEY ):\n2015-04-04 17:02:20 139944445957952 Starting new HTTPS connection (1):\n127.0.0.1\n2015-04-04 17:02:20 139944445957952 Could not connect to CRITs when\nsubmitting domain kmlky.com\n2015-04-04 17:02:20 139944445957952 Starting new HTTPS connection (1):\n127.0.0.1\n2015-04-04 17:02:23 139944445957952 \"POST /api/v1/samples/ HTTP/1.1\" 200\nNone\n2015-04-04 17:02:23 139944445957952 Saved 927963665ed539335b740f704a3d546f\nto dump dir\n2015-04-04 17:02:23 139944445957952\nhxxp://healthygarcinialifestyle[.]com/wp-content/old/\nPaypal.co.uk/login/PP1/myaccount/147c1/home?cmd=_account-details&session=2439328f21281f85a23af8649ca47a4b&dispatch=6e0b2cd81e08706e9667626b79394a77be5598b0\nhashes to 1bc3e8566b264866db13d93a8d5c446d\n2015-04-04 17:02:23 139944445957952 Domain submission:\nhttps://127.0.0.1/api/v1/domains/|{'username': 'maltrieve', 'source':\n'maltrieve', 'domain': u'healthygarcinialifestyle[.]com', 'api_key':\n'MYAPIKEY'}\nThe version of CRITs I am running is: 4-master. Any logs etc., I can\nprovide please let me know and thanks for this awesome tool !\n\u2014\nReply to this email directly or view it on GitHub.\n. Do you mind sending me a snippet of your Apache error log during this time? \n\nI have seen this before when CRITs overloads. However the CRITs team was recently working on their parsers so I want to make sure that didn't change anything as well.\nUsually I track with master. However, I am running some ML tests right now. So I am about a month behind what is current so I don't break anything. :)\nSent from my iPhone\n\nOn 05 Apr 2015, at 03:55, markmaunu notifications@github.com wrote:\nLet me know if I can provide anything else to debug . Are you uploading to 4-master ?\n\u2014\nReply to this email directly or view it on GitHub.\n. Something is going on. I dont like that IOError error you are receiving\ncan you do:\n1) tail -n 500 /var/log/apache2/error.log\n2) tail -n 500 /logs/crits.log\n\nbtw you are welcome to send me the logs privately if you dont want to\nexpose your system details. granted all your ip's are private so I doubt it\nmatters all that much. Anyway, my email is webstergd@sec.in.tum.de\nOn Sun, Apr 5, 2015 at 5:38 PM, markmaunu notifications@github.com wrote:\n\nSure : Below are the tail end of /var/log/apache2/error.log from running\nlast night . My version of CRITs is definitely in sync with current\n4_master.\n[Sat Apr 04 17:03:37.642249 2015] [:error] [pid 16537:tid 139835754874624]\nException OSError: (2, 'No such file or directory',\n'/tmp/tmpsARj25.upload') in ', mode 'w+b' at 0x7f2df37d8660>> ignored\n[Sat Apr 04 17:03:37.668567 2015] [:error] [pid 16537:tid 139835754874624]\nException OSError: (2, 'No such file or directory',\n'/tmp/tmpd0FPzq.upload') in ', mode 'w+b' at 0x7f2df55dcae0>> ignored\n[Sat Apr 04 17:03:37.669050 2015] [:error] [pid 16537:tid 139835754874624]\nException OSError: (2, 'No such file or directory',\n'/tmp/tmpctSgRJ.upload') in ', mode 'w+b' at 0x7f2df558d1e0>> ignored\n[Sat Apr 04 17:03:37.675781 2015] [:error] [pid 16537:tid 139835754874624]\nException OSError: (2, 'No such file or directory',\n'/tmp/tmpuz3Bcq.upload') in ', mode 'w+b' at 0x7f2df55dcc00>> ignored\n[Sat Apr 04 17:03:37.686269 2015] [:error] [pid 16537:tid 139835754874624]\nException OSError: (2, 'No such file or directory',\n'/tmp/tmpipa4KR.upload') in ', mode 'w+b' at 0x7f2df55dca50>> ignored\n[Sat Apr 04 18:58:29.999979 2015] [:error] [pid 8987:tid 139835704518400]\n[client 192.168.1.102:9502] mod_wsgi (pid=8987): Exception occurred\nprocessing WSGI script '/data/crits/django.wsgi'., referer:\nhttps://192.168.1.110/\n[Sat Apr 04 18:58:30.000255 2015] [:error] [pid 8987:tid 139835704518400]\n[client 192.168.1.102:9502] IOError: failed to write data, referer:\nhttps://192.168.1.110/\n[Sat Apr 04 18:58:35.527260 2015] [:error] [pid 8987:tid 139835830408960]\n[client 192.168.1.102:9504] mod_wsgi (pid=8987): Exception occurred\nprocessing WSGI script '/data/crits/django.wsgi'., referer:\nhttps://192.168.1.110/samples/details/ab90bae7260159d26869c79296b2cea2/\n[Sat Apr 04 18:58:35.527321 2015] [:error] [pid 8987:tid 139835830408960]\n[client 192.168.1.102:9504] IOError: failed to write data, referer:\nhttps://192.168.1.110/samples/details/ab90bae7260159d26869c79296b2cea2/\n[Sat Apr 04 18:59:57.175140 2015] [core:warn] [pid 8983:tid\n139836067473280] AH00045: child process 8986 still did not exit, sending a\nSIGTERM\n[Sat Apr 04 18:59:59.178522 2015] [core:warn] [pid 8983:tid\n139836067473280] AH00045: child process 8986 still did not exit, sending a\nSIGTERM\n[Sat Apr 04 19:00:01.181126 2015] [core:warn] [pid 8983:tid\n139836067473280] AH00045: child process 8986 still did not exit, sending a\nSIGTERM\n[Sat Apr 04 19:00:03.184027 2015] [core:error] [pid 8983:tid\n139836067473280] AH00046: child process 8986 still did not exit, sending a\nSIGKILL\n[Sat Apr 04 19:00:04.187743 2015] [mpm_event:notice] [pid 8983:tid\n139836067473280] AH00491: caught SIGTERM, shutting down\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/krmaxwell/maltrieve/issues/150#issuecomment-89794721.\n. Hey it looks like the issue is being caused by an overload on the CRITs server. mark and I are going to continue to monitor this and if this is really the case I will update the readme that discusses this. \n\nWill keep you posted\n. I am happy to do this but I would worry about false positives. Since these\nare typically download sites, I would expect some cross over with benign\ndomains because the domains can and appear to be often hijacked. I am doing\na study on this right now (should be finished by the end of May) and if you\nwant I say lets table this until we have the results.\nIf people want this now, just let me know and I will code it up pretty\nquickly for you.\nOn Sun, Apr 5, 2015 at 3:45 AM, Kyle Maxwell notifications@github.com\nwrote:\n\nUse \"URI - URL\" as the Indicator type.\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/krmaxwell/maltrieve/issues/151.\n. -            self.crits = args.crits or self.configp.get('Maltrieve', 'crits')\n-            self.crits = self.configp.get('Maltrieve', 'crits')\n\nIn my setup that caused self.crits to be equal to True\n-            domain_response = requests.post(url, headers=headers, data=domain_data)\n-            domain_response = requests.post(url, headers=headers, data=domain_data, verify=False)\nFor some reason without that verify it breaks. Check your setup and look at domains and relationships. It will upload the samples but fails on the domain and creating the relationship. (I am using a valid ssl)\n. The developmental version of CRITs has some core changes to to the\nAuthenticated API handlers. I have a patch to fix. However, the CRITs API\nis still in flux...or at least last I checked.\nOn Tue, Feb 9, 2016 at 11:57 PM, Michael Boman notifications@github.com\nwrote:\n\n2016-02-09 23:51:59 140185836697408 \"POST /api/v1/relationships/ HTTP/1.1\"\n403 None\n2016-02-09 23:51:59 140185836697408 Submitted relationship info for\nb67b6e808ded0adb1ee3ba1d072bf6d5 to CRITs, response was {u'url':\nu'/api/v1/domains/56b7a2e558d296749bf0a8d3/', u'message': u'Updated\nexisting domain: get.bb0413fllc.info\nhttp:///domains/details/get.bb0413fllc.info/', u'type': u'Domain',\nu'return_code': 0, u'id': u'56b7a2e558d296749bf0a8d3'}\nAdding sample and domain works fine though.\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/krmaxwell/maltrieve/issues/179.\n. I dont have time to check to make sure it still works. But you can find the\ncode that contains the updated API calls here:\nhttps://github.com/webstergd/maltrieve\n\nOn Wed, Feb 10, 2016 at 12:24 AM, George Webster webstergd@gmail.com\nwrote:\n\nThe developmental version of CRITs has some core changes to to the\nAuthenticated API handlers. I have a patch to fix. However, the CRITs API\nis still in flux...or at least last I checked.\nOn Tue, Feb 9, 2016 at 11:57 PM, Michael Boman notifications@github.com\nwrote:\n\n2016-02-09 23:51:59 140185836697408 \"POST /api/v1/relationships/\nHTTP/1.1\" 403 None\n2016-02-09 23:51:59 140185836697408 Submitted relationship info for\nb67b6e808ded0adb1ee3ba1d072bf6d5 to CRITs, response was {u'url':\nu'/api/v1/domains/56b7a2e558d296749bf0a8d3/', u'message': u'Updated\nexisting domain: get.bb0413fllc.info\nhttp:///domains/details/get.bb0413fllc.info/', u'type': u'Domain',\nu'return_code': 0, u'id': u'56b7a2e558d296749bf0a8d3'}\nAdding sample and domain works fine though.\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/krmaxwell/maltrieve/issues/179.\n. \n\n",
    "ghost": "You can scope limit to the process level within Python\nimport resource\nresource.setrlimit(resource.RLIMIT_NOFILE, (65536, 65536))\nhttps://docs.python.org/2/library/resource.html\n. Current implementation is working fine with Python version 2.7.9\nEnsure you have installed the requirements \npip install -r requirements.txt\n\u250c\u2500[10:33:52]\u2500[alienone@binary]\n\u2514\u2500\u2500> maltrieve $ >> /home/alienone/anaconda/bin/python maltrieve.py\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\n\n. Running all the way through - will see if I can recreate your problem set via running 2nd round after 1st round completion. \n. Just for the record the type(malware_urls) on line 309 on 1st round execution comes back as expected type set. c0den since you can run 2nd round - put a print statement at line 309\nprint(type(malware_urls))\nmalware_urls -= past_urls\n. Hmm odd - I just forked the entire project - let me do a git pull - \nSo add at line 325 print statement so looks like this for lines 325 and 326\nprint(type(malware_urls))\nmalware_urls -= past_urls\n. pulled from main repo so we are on same sheet of music now - line 326 \n. Correction  - Line 295 needs to output a set data structure and not a list data structure \na_set = {1, 2, 3, 4}\na_list = [5, 6, 7, 8]\nb_set = {3, 4, 7, 8}\na_set -= b_set\nprint(a_set)\na_set -= a_list\nset([1, 2])\n\nTypeError                                 Traceback (most recent call last)\n in ()\n      4 a_set -= b_set\n      5 print(a_set)\n----> 6 a_set -= a_list\n      7 \nTypeError: unsupported operand type(s) for -=: 'set' and 'list'\n\n. There we go - testing \n. ",
    "dray0n": "I was having the same issues on a fresh install. I was able to remedy the issue:\n$ ulimit -a \nopen files     (-n) 1024\n$ ulimit -n 2048\nMaltrieve has now been running for 30 minutes without an issue.  Before, I was erroring out after about 5-10 minutes of running.\n. I am going to load the rlimit branch right now.... but as a note I received the error again. Roughly 45-minutes in.\n. $  netstat -an \nHundreds of \"CLOSE_WAIT\"'s out there.\n. Been awhile...  I was going through the dependencies and found out that I did not have all of the requirements met for some reason.   Problem solved through a few issues on missing packages and was finally able to get all requirements met.\nOpen socket issue is no longer an issue.\n. The process I have with Maltrieve is to run on cron as well as submit to my cuckoo instance.   Nice automated analysis. :)\n. userr@box:~/scripts/maltrieve$ curl -x http://127.0.0.1:8118 icanhazip.com\n46.182.106.190\nuser@box:~/scripts/maltrieve$ ./maltrieve.py -p 127.0.0.1:8118 -d ~/malware\nLog:\n2015-02-04 20:13:28 140520711960384 Using proxy {'http': '127.0.0.1:8118'}\n2015-02-04 20:13:28 140520711960384 Starting new HTTP connection (1): icanhazip.com\n2015-02-04 20:13:29 140520711960384 \"GET /?ipraw HTTP/1.1\" 200 13\n2015-02-04 20:13:29 140520711960384 External sites see <Home IP>\n`\\\n. Thank you. It might be nice to echo the IP information to the console as well. In the event someone doesn't view the log...  \nThat feature may even be nice for as a standard echo to console.  I have changed the vm that this runs on to route all traffic through Tor now.  Always nice to feel a bit safer. :)\n. Ran the proxy-fix branch -- IP echo in shell reflects a Tor-routed IP address.  Problem solved!\n. > TypeError: set([u'http://website.com/blah.exe', continued array of urls]) is not JSON serializable\n. Verified -- Maltrieve is working as intended. Thanks Kyle!\n. ",
    "jebelingmi": "just got same issue reported above on fresh install today.\njeff@ubuntu64:~/maltrieve$  python /home/jeff/maltrieve/maltrieve.py -l logfile.txt -p http://192.168.11.122:9090 -d /home/jeff/maltrieve/malware/              External sites see 68.40.253.188\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nTraceback (most recent call last):\n  File \"/home/jeff/maltrieve/maltrieve.py\", line 514, in \n  File \"/home/jeff/maltrieve/maltrieve.py\", line 503, in main\n  File \"/home/jeff/maltrieve/maltrieve.py\", line 340, in save_malware\nIOError: [Errno 24] Too many open files: '/home/jeff/maltrieve/malware/bbc0dacb709608260751692405972b7b'\n. How can I tell what version? I made the modification to correct issue with \"key error u'http\" on whatever version I was running. Going to try downloading latest. Can I just m. sudo git clone https://github.com/technoskald/maltrieve.git ?\nCDDB==1.4\nCython==0.22\nGnuPGInterface==0.3.2\nPAM==0.4.2\nPillow==2.3.0\nTwisted-Core==13.2.0\nTwisted-Web==13.2.0\napt-xapian-index==0.45\nargparse==1.2.1\nbeautifulsoup4==4.3.2\nchardet==2.0.1\ncolorama==0.2.5\ncommand-not-found==0.3\ndebtagshw==0.1\ndefer==1.0.6\ndirspec==13.10\nfeedparser==5.1.3\ngevent==1.0.1\ngreenlet==0.4.5\ngrequests==0.2.0\nhtml5lib==0.999\nhttplib2==0.8\nlxml==3.3.3\nmutagen==1.22\noauthlib==0.6.1\noneconf==0.3.7\npexpect==3.1\npiston-mini-client==0.7.5\npsutil==1.2.1\npyOpenSSL==0.13\npycrypto==2.6.1\npycups==1.9.66\npygobject==3.12.0\npyserial==2.6\npysmbc==1.0.14.1\npython-apt==0.9.3.5ubuntu1\npython-debian==0.1.21-nmu2ubuntu2\npython-magic==0.4.6\npyxdg==0.25\nreportlab==3.0\nrequests==2.2.1\nsessioninstaller==0.0.0\nsix==1.5.2\nsoftware-center-aptd-plugins==0.0.0\nsystem-service==0.1.6\nunity-lens-photos==1.0\nurllib3==1.7.1\nwsgiref==0.1.2\nzope.interface==4.0.5\n. Updated to latest version and made the change to remove the key error and working now thanks!\n. Same one listed in the recent bug. Had to change entry for vxvault to vxvault.net\n. ",
    "bambenek": "Oof, let me get back to this and test... got distracted on other projects.\nOn 2/5/2015 4:28 PM, Kyle Maxwell wrote:\n\nIs this still an issue? I suspect you have the wrong module for |magic|.\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/technoskald/maltrieve/issues/74#issuecomment-73143586.\n. \n",
    "panw-ren": "I'm getting the same error on my end. I'm hoping to get some help. Here's the pip freeze output on my host. thanks in advance.\nMagic-file-extensions==0.2\nPAM==0.4.2\nPillow==2.3.0\nTwisted-Core==13.2.0\nTwisted-Web==13.2.0\nadium-theme-ubuntu==0.3.4\napt-xapian-index==0.45\nargparse==1.2.1\nbeautifulsoup4==4.2.1\nchardet==2.0.1\ncolorama==0.2.5\ncommand-not-found==0.3\ndebtagshw==0.1\ndefer==1.0.6\ndirspec==13.10\nduplicity==0.6.23\nfeedparser==5.1.3\ngevent==1.0\ngreenlet==0.4.2\nhtml5lib==0.999\nhttplib2==0.8\nlockfile==0.8\nlxml==3.3.3\noauthlib==0.6.1\noneconf==0.3.7\npexpect==3.1\npiston-mini-client==0.7.5\npyOpenSSL==0.13\npycrypto==2.6.1\npycups==1.9.66\npycurl==7.19.3\npygobject==3.12.0\npyserial==2.6\npysmbc==1.0.14.1\npython-apt==0.9.3.5\npython-debian==0.1.21-nmu2ubuntu2\npyxdg==0.25\nreportlab==3.0\nrequests==2.2.1\nsessioninstaller==0.0.0\nsix==1.5.2\nsoftware-center-aptd-plugins==0.0.0\nssh-import-id==3.21\nsystem-service==0.1.6\nunity-lens-photos==1.0\nurllib3==1.7.1\nwsgiref==0.1.2\nxdiagnose==3.6.3build2\nzope.interface==4.0.5\n. Thanks Kyle!\n. Having the same issue. \nattrs==15.2.0\nBeautifulSoup==3.2.1\nbeautifulsoup4==4.5.3\nbs4==0.0.1\nchardet==2.3.0\nconfigobj==5.0.6\ncryptography==1.2.3\necdsa==0.13\nenum34==1.1.2\nfeedparser==5.2.1\ngevent==1.2.1\ngreenlet==0.4.12\nidna==2.0\nipaddress==1.0.16\nLandscape-Client==16.3+bzr834\nndg-httpsclient==0.4.0\nPAM==0.4.2\nparamiko==1.16.0\npyasn1==0.1.9\npyasn1-modules==0.0.7\npycrypto==2.6.1\npyOpenSSL==0.15.1\npyserial==3.0.1\npython-apt==1.1.0b1\npython-debian==0.1.27\npython-magic==0.4.12\nrequests==2.13.0\nscapy==2.3.3\nservice-identity==16.0.0\nsix==1.10.0\nTwisted==16.0.0\nzope.interface==4.1.3\nuser1@ubuntu-template:~/maltrieve/maltrieve-0.7/files$ lsb_release -a\nNo LSB modules are available.\nDistributor ID: Ubuntu\nDescription:    Ubuntu 16.04.1 LTS\nRelease:        16.04\nCodename:       xenial\nuser1@ubuntu-template:~/maltrieve/maltrieve-0.7$ sudo ./maltrieve.py\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nCompleted downloads\nuser1@ubuntu-template:~/maltrieve/maltrieve-0.7$ more urls.json\n[]\nuser1@ubuntu-template:~/maltrieve/maltrieve-0.7$ sudo ./maltrieve.py -d ./files/\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nCompleted downloads\nuser1@ubuntu-template:~/maltrieve/maltrieve-0.7$ cd files/\nuser1@ubuntu-template:~/maltrieve/maltrieve-0.7/files$ ls\nuser1@ubuntu-template:~/maltrieve/maltrieve-0.7/files$\n. utilized the other branch as mentioned by hi-T0day but still no luck\nuser1@ubuntu-template:~/maltrieve-0.7$ sudo ./maltrieve.py -d /home/user1/malware\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nCompleted downloads\nuser1@ubuntu-template:~/maltrieve-0.7$ cd /home/user1/malware/\nuser1@ubuntu-template:~/malware$ ls\nuser1@ubuntu-template:~/malware$\nhashesh.json/urls.json files are empty\n2017-03-13 16:13:32 140601425241856 Loaded urls from urls.json\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): support.clean-mx.de\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): www.malwaredomainlist.com\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): vxvault.siri-urz.net\n2017-03-13 16:13:32 140601425241856 Starting new HTTPS connection (1): zeustracker.abuse.ch\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): urlquery.net\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): malwareurls.joxeankoret.com\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): malc0de.com\n2017-03-13 16:13:32 140601425241856 http://www.malwaredomainlist.com:80 \"GET /hostslist/mdl.xml HTTP/1.1\" 200 5735\n2017-03-13 16:13:33 140601425241856 https://zeustracker.abuse.ch:443 \"GET /monitor.php?urlfeed=binaries HTTP/1.1\" 200 3882\n2017-03-13 16:13:33 140601425241856 http://malwareurls.joxeankoret.com:80 \"GET /normal.txt HTTP/1.1\" 200 11192\n2017-03-13 16:13:33 140601425241856 http://malc0de.com:80 \"GET /rss/ HTTP/1.1\" 200 None\n2017-03-13 16:13:33 140601425241856 http://urlquery.net:80 \"GET / HTTP/1.1\" 200 4703\n2017-03-13 16:13:34 140601425241856 http://support.clean-mx.de:80 \"GET /clean-mx/rss?scope=viruses&limit=0%2C64 HTTP/1.1\" 200 918\n2017-03-13 16:13:34 140601425241856 Dumping past URLs to urls.json\n2017-03-13 16:13:34 140601425241856 Dumping hashes to hashes.json\nuser1@ubuntu-template:~/maltrieve-0.7$ more hashes.json\n[]\nuser1@ubuntu-template:~/maltrieve-0.7$ more urls.json\n[]\n. are people still able to get help on issues w/ maltrieve?. ",
    "Sh4d0wS4int": "yeah the crawler is epic :) but what i thought is that it could be like a optional virustotal support which could store the Hashes in the HTML/DB (Json response) which could provide the ease the work of the initial static analysis just my suggestion though.\n. why i said this because we have cuckoo and others sandbox support why not virustotal after first thing people do is scan in virustotal well if you guys think it is a scope creep then it is fine with me \n. well there is one drawback to that public api key has a limitation regarding post Requests\nhttps://www.virustotal.com/en/documentation/public-api/ \nscan time too seems to be a issue \n. ",
    "Healwhans": "urls.json is empty.\n. After downloading the newer version of maltrieve, the error went away. Thanks for your help.\n. IDK why but the versions I've downloaded from the maltrieve website do not include setup.py. I'm closing this issue because the question has been answered.\nThanks!\n. Can you tell I don't read? I skim. Gets me in all sorts of trouble... :0) Thanks for your hard work keeping maltrieve current!\n. ",
    "wessorh": "lets all hope, not.\n-rick\nOn Sat, Feb 28, 2015 at 5:05 PM, Kyle Maxwell notifications@github.com\nwrote:\n\n...maybe...\n\u2014\nReply to this email directly or view it on GitHub\nhttps://github.com/krmaxwell/maltrieve/issues/88#issuecomment-76562015.\n. \n",
    "c0den": "0 bytes\n. This could be a result of the following bug \"Output Shows Not JSON Serialized After Running\"..this has not been confirmed but I remember seeing a similar error on the previous execution of maltrieve before the execution that yielded the bug I reported.\n. @krmaxwell confirm Fix #90. Created an empty urls.json file and confirmed error...applied patch and it fixed the issue. Thanks\n. So after a complete run it did create the urls.json file and it is populated.\n. @alienone It runs fine on the first launch but after it creates the urls.json file it won't run again and I get that error. Just to verify I pulled it down in a sandbox did a pip install -r requirements.txt and am still getting the same error after the second run.\n. Have you pulled the recent changes since yesterday? Line 309 within my maltrieve.py contains \"                   'http://support.clean-mx.de/clean-mx/rss?scope=viruses&limit=0%2C64': process_xml_list_title,\n\"\n. I get the following after adding:\nprint(type(malware_urls))\nprint(type(past_urls))\nThis is first run:\n-> % ./maltrieve.py\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\n\n\nThis is second run:\n-> % ./maltrieve.py\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\n\n\nTraceback (most recent call last):\n  File \"./maltrieve.py\", line 353, in \n    main()\n  File \"./maltrieve.py\", line 327, in main\n    malware_urls -= past_urls\nTypeError: unsupported operand type(s) for -=: 'set' and 'list'\nI think it is line 344 causing the type change:\n341   if past_urls:\n342        logging.info('Dumping past URLs to file')\n343       with open('urls.json', 'w') as urlfile:\n344            json.dump(list(past_urls), urlfile)\n. Sorry \nThis is first run:\n-> % ./maltrieve.py\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\ntype 'set'\ntype 'set'\nThis is second run:\n-> % ./maltrieve.py\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\ntype 'set'\ntype 'list'\nTraceback (most recent call last):\n  File \"./maltrieve.py\", line 353, in \n    main()\n  File \"./maltrieve.py\", line 327, in main\n    malware_urls -= past_urls\nTypeError: unsupported operand type(s) for -=: 'set' and 'list'\n. Confirmed working now.\n. ",
    "landscape-bot": "\nCode quality remained the same when pulling ed5eda9 on krmaxwell:i58-timeout into 551871d on krmaxwell:dev.\n. \nCode quality remained the same when pulling c92e060 on krmaxwell:i58-timeout into 551871d on krmaxwell:dev.\n. ",
    "ryan00": "This is still a work in progress, I will open a proper pull request once complete.\n_ryan\nOn April 2, 2015 at 2:38:53 PM, Kyle Maxwell (notifications@github.com) wrote:\nThis looks fun, actually!\n\u2014\nReply to this email directly or view it on GitHub.\n. Sounds good.\nThanks\n_ryan\nOn April 2, 2015 at 2:41:19 PM, Kyle Maxwell (notifications@github.com) wrote:\nNo worries, I like where it's headed though.\nOne thing - please open the PR against the dev branch for ease of management. And feel free to ask any questions you might have!\n\u2014\nReply to this email directly or view it on GitHub.\n. ",
    "eldraco": "Perfect! thanks a lot. Now is working.\n. ",
    "jrespeto": "I was getting security errors also did this to fix it. \napt-get install libffi-dev openssl-dev\npip install requests[security]\n. PR #177 was submitted to fix \"Invalid URL u'True/file/add'\"\n. PR #177 was sibmitted to fix the Invalid URL 'True/malware/add':\n. Hi, \nMaltrieve is an awesome tool!\nI'm really new to python programing  but I got a friend of mine from work look at the error with me. We traced the issues to the \"class config(object):\"\nfrom the error log \nrequests.exceptions.MissingSchema: Invalid URL u'True/file/add': No schema supplied. \nline 289 =>        url = \"{srv}/file/add\".format(srv=cfg.viper)\n.format(srv=cfg.viper)  is returning True\n\n119         # TODO: Merge these\n120         self.vxcage = args.vxcage or self.configp.has_option('Maltrieve', 'vxcage')\n121         self.cuckoo = args.cuckoo or self.configp.has_option('Maltrieve', 'cuckoo')\n122         self.viper = args.viper or self.configp.has_option('Maltrieve', 'viper')\n\nShould be this like in the # CRITs section. \n# TODO: Merge these\n    if args.vxcage or self.configp.has_option('Maltrieve', 'vxcage'):\n        self.vxcage = self.configp.get('Maltrieve', 'vxcage')\n    if args.cuckoo or self.configp.has_option('Maltrieve', 'cuckoo'):\n        self.cuckoo = self.configp.get('Maltrieve', 'cuckoo')\n    if args.viper or self.configp.has_option('Maltrieve', 'viper'):\n        self.viper = self.configp.get('Maltrieve', 'viper')\n\nWill let you know if I run into other things. \nThank you, \nJonathan\n. Hi Kyle, \nAny update on this pull request. \nJon\n. ",
    "markmaunu": "Hey guys this is exactly the case the domain is not there but all of the samples get added.\n. It looks like the last successful correlation I have is on 4-2-15 for a domain that was originally added and a sample pulled on 3-31-15.\n\nflv3.dmrcdn[.]com   2015-04-02 05:46:49 maltrieve       New \ndmrcdn[.]com    2015-04-02 05:46:45 maltrieve       New \nthejsscripts[.]com  2015-04-02 05:46:34 maltrieve       New \nwww[.]solvusoft[.]com   2015-04-02 05:46:29  maltrieve  New\nScreenshot added for first domain listed above showing correlation \n. Just verified that I have access to the source - added cnn.com successfully\n\n. Attached is a sample that uploaded today through maltrieve.\n\n. Let me know if I can provide anything else to debug . Are you uploading to 4-master ?\n. Sure : Below are the tail end of /var/log/apache2/error.log from running last night . My version of CRITs is definitely in sync with current 4_master. \n[Sat Apr 04 17:03:37.642249 2015] [:error] [pid 16537:tid 139835754874624] Exception OSError: (2, 'No such file or directory', '/tmp/tmpsARj25.upload') in ', mode 'w+b' at 0x7f2df37d8660>> ignored\n[Sat Apr 04 17:03:37.668567 2015] [:error] [pid 16537:tid 139835754874624] Exception OSError: (2, 'No such file or directory', '/tmp/tmpd0FPzq.upload') in ', mode 'w+b' at 0x7f2df55dcae0>> ignored\n[Sat Apr 04 17:03:37.669050 2015] [:error] [pid 16537:tid 139835754874624] Exception OSError: (2, 'No such file or directory', '/tmp/tmpctSgRJ.upload') in ', mode 'w+b' at 0x7f2df558d1e0>> ignored\n[Sat Apr 04 17:03:37.675781 2015] [:error] [pid 16537:tid 139835754874624] Exception OSError: (2, 'No such file or directory', '/tmp/tmpuz3Bcq.upload') in ', mode 'w+b' at 0x7f2df55dcc00>> ignored\n[Sat Apr 04 17:03:37.686269 2015] [:error] [pid 16537:tid 139835754874624] Exception OSError: (2, 'No such file or directory', '/tmp/tmpipa4KR.upload') in ', mode 'w+b' at 0x7f2df55dca50>> ignored\n[Sat Apr 04 18:58:29.999979 2015] [:error] [pid 8987:tid 139835704518400] [client 192.168.1.102:9502] mod_wsgi (pid=8987): Exception occurred processing WSGI script '/data/crits/django.wsgi'., referer: https://192.168.1.110/\n[Sat Apr 04 18:58:30.000255 2015] [:error] [pid 8987:tid 139835704518400] [client 192.168.1.102:9502] IOError: failed to write data, referer: https://192.168.1.110/\n[Sat Apr 04 18:58:35.527260 2015] [:error] [pid 8987:tid 139835830408960] [client 192.168.1.102:9504] mod_wsgi (pid=8987): Exception occurred processing WSGI script '/data/crits/django.wsgi'., referer: https://192.168.1.110/samples/details/ab90bae7260159d26869c79296b2cea2/\n[Sat Apr 04 18:58:35.527321 2015] [:error] [pid 8987:tid 139835830408960] [client 192.168.1.102:9504] IOError: failed to write data, referer: https://192.168.1.110/samples/details/ab90bae7260159d26869c79296b2cea2/\n[Sat Apr 04 18:59:57.175140 2015] [core:warn] [pid 8983:tid 139836067473280] AH00045: child process 8986 still did not exit, sending a SIGTERM\n[Sat Apr 04 18:59:59.178522 2015] [core:warn] [pid 8983:tid 139836067473280] AH00045: child process 8986 still did not exit, sending a SIGTERM\n[Sat Apr 04 19:00:01.181126 2015] [core:warn] [pid 8983:tid 139836067473280] AH00045: child process 8986 still did not exit, sending a SIGTERM\n[Sat Apr 04 19:00:03.184027 2015] [core:error] [pid 8983:tid 139836067473280] AH00046: child process 8986 still did not exit, sending a SIGKILL\n[Sat Apr 04 19:00:04.187743 2015] [mpm_event:notice] [pid 8983:tid 139836067473280] AH00491: caught SIGTERM, shutting down\n. Sure thing. I'll send them privately just not to muddy up the thread.\n. ",
    "tysonmax20042003": "Here is the output. I do have python-magic installed. I thought it was that causing the problem. Thanks for looking at the problem. \npip freeze output:\nBeautifulSoup==3.2.1\nDjango==1.6.1\nJinja2==2.7.2\nLandscape-Client==14.12\nMagic-file-extensions==0.2\nMako==0.9.1\nMarkupSafe==0.18\nPAM==0.4.2\nPillow==2.3.0\nPyrex==0.9.8.5\nSQLAlchemy==0.8.4\nTwisted-Core==13.2.0\napt-xapian-index==0.45\nargparse==1.2.1\nbeautifulsoup4==4.3.2\nbottle==0.12.0\nchardet==2.0.1\ncolorama==0.2.5\nconfigobj==4.7.2\ndnspython==1.11.1\ndpkt==1.6\nfeedparser==5.1.3\ngevent==1.0.1\ngreenlet==0.4.5\nhtml5lib==0.999\nlibvirt-python==1.2.2\nlxml==3.3.3\nnose==1.3.1\nopenpyxl==1.7.0\npefile==1.2.9.1\npyOpenSSL==0.13\npycrypto==2.6.1\npydeep==0.2\npymongo==2.6.3\npyserial==2.6\npython-apt==0.9.3.5ubuntu1\npython-debian==0.1.21-nmu2ubuntu2\nrequests==2.2.1\nsix==1.5.2\nssh-import-id==3.21\nurllib3==1.7.1\nvolatility==2.3.1\nwsgiref==0.1.2\nyara-python==3.3.0\nzope.interface==4.0.5\n. It worked?!? I thought I had it installed. Thanks for fixing my easy answer. Oh, I have a quick question that is not related. Can I send all Malware to a Cuckoo instance by chance? I would imagine I would need to run Maltrieve then maltrievecategorizer then see if I can get Cuckoo to analyse all files in a folder or can I send it from Maltrieve?\n. ",
    "jwils0n0x": "Confirmed fixed for me.  Thanks!\n. ",
    "sooshie": "Yeah, the tests that failed are for functions that don't exist because all that stuff was moved externally (to the plugins). I'd suggest removing the tests, but let me know what you'd like to do.\n. Fixed the failed tests, looks like the one that failed was because you're checking the links in the README and the site is down.\n. ",
    "trogdorsey": "Is anything ever going to become of this?\n. ",
    "apolkosnik-old": "It looks like today is not a good day for improvization. \n. ",
    "johnfellers": "i had the same issue...\ni fixed this by running\n$ sudo pip install LinkChecker==9.3\nthen rerun sudo pip install -r requirements.txt\n. ",
    "clayball": "I can confirm.. nothing is being downloaded.. ",
    "lhunt23": "Thanks for the follow up. If you have any suggestions as to how to get the script working again, please let me know. I've found this script to be extremely useful and appreciate you making it available.. Hello,\nThanks for your response. I made the suggested changes and the script still isn\u2019t downloading files.  Please let me know if you have any additional suggestions. Thanks.\ndef process_urlquery(response):\n    soup = BeautifulSoup(response, \"html.parser\")\n    urls = set()\n    for t in soup.find_all(\"table\", class_=\"test\"):\n        for a in t.find_all(\"a\"):\n            urls.add('http://' + re.sub('&', '&', a.text))\n    return urls\nroot@ubuntu:~/scripts/maltrieve-master# python maltrieve.py\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nCompleted downloads\nFrom: hi-T0day [mailto:notifications@github.com]\nSent: Saturday, March 04, 2017 7:31 AM\nTo: krmaxwell/maltrieve maltrieve@noreply.github.com\nCc: Lindsay Hunt lhunt@paloaltonetworks.com; Author author@noreply.github.com\nSubject: Re: [krmaxwell/maltrieve] files aren't downloaded (#182)\nSorry, I gave you an wrong answer just now. But I got it now.\nYou can change in \"maltrieve.py\"\ndef process_urlquery(response):\nsoup = BeautifulSoup(response)\nurls = set()\nfor t in soup.find_all(\"table\", class_=\"test\"):\nfor a in t.find_all(\"a\"):\nurls.add('http://' + re.sub('&', '&', a.text))\nreturn urls\nto:\ndef process_urlquery(response):\nsoup = BeautifulSoup(response, \"html.parser\")\nurls = set()\nfor t in soup.find_all(\"table\", class_=\"test\"):\nfor a in t.find_all(\"a\"):\nurls.add('http://' + re.sub('&', '&', a.text))\nreturn urls\n\u2014\nYou are receiving this because you authored the thread.\nReply to this email directly, view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_krmaxwell_maltrieve_issues_182-23issuecomment-2D284148635&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=q5gVyZzvxIN7Ph17gPhHTO7Q4aRkyOZ3mFKqvntA0Is&s=Bo83Xt6s_y-i4zVfjz2RploQJkZU9XGrLykpI64rA1I&e=, or mute the threadhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYWdcofBGCSbHHGMCdu44BJXxVTK8oyxks5riVl5gaJpZM4L3jQB&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=q5gVyZzvxIN7Ph17gPhHTO7Q4aRkyOZ3mFKqvntA0Is&s=bYq5lVPDDGgRSi42bxp-2wHPiMbGqrvR1YoaWdCdWz4&e=.\n. Hello,\nPlease see below and let me know if you have any suggestions.\npython maltrieve.py -d /home/lhunt/malware/030817/\nTraceback (most recent call last):\n  File \"maltrieve.py\", line 580, in \n    main()\n  File \"maltrieve.py\", line 520, in main\n    cfg = config(args, 'maltrieve.cfg')\n  File \"maltrieve.py\", line 131, in init\n    self.cuckoo_dist = self.configp.get('Maltrieve', 'cuckoo_dist')\n  File \"/usr/lib/python2.7/ConfigParser.py\", line 623, in get\n    return self._interpolate(section, option, value, d)\n  File \"/usr/lib/python2.7/ConfigParser.py\", line 669, in _interpolate\n    option, section, rawval, e.args[0])\nConfigParser.InterpolationMissingOptionError: Bad value substitution:\n        section: [Maltrieve]\n        option : cuckoo_dist\n        key    : dist_port_9003_tcp_addr\n        rawval : http://%(DIST_PORT_9003_TCP_ADDR)s:9003http://%25(DIST_PORT_9003_TCP_ADDR)s:9003\nsudo python maltrieve.py\nTraceback (most recent call last):\n  File \"maltrieve.py\", line 580, in \n    main()\n  File \"maltrieve.py\", line 520, in main\n    cfg = config(args, 'maltrieve.cfg')\n  File \"maltrieve.py\", line 131, in init\n    self.cuckoo_dist = self.configp.get('Maltrieve', 'cuckoo_dist')\n  File \"/usr/lib/python2.7/ConfigParser.py\", line 623, in get\n    return self._interpolate(section, option, value, d)\n  File \"/usr/lib/python2.7/ConfigParser.py\", line 669, in _interpolate\n    option, section, rawval, e.args[0])\nConfigParser.InterpolationMissingOptionError: Bad value substitution:\n        section: [Maltrieve]\n        option : cuckoo_dist\n        key    : dist_port_9003_tcp_addr\n        rawval : http://%(DIST_PORT_9003_TCP_ADDR)s:9003http://%25(DIST_PORT_9003_TCP_ADDR)s:9003\npython3 maltrieve.py\n  File \"maltrieve.py\", line 125\n    self.priority = args.priority\n                                ^\nTabError: inconsistent use of tabs and spaces in indentation\nFrom: hi-T0day [mailto:notifications@github.com]\nSent: Wednesday, March 08, 2017 3:20 AM\nTo: krmaxwell/maltrieve maltrieve@noreply.github.com\nCc: Lindsay Hunt lhunt@paloaltonetworks.com; Author author@noreply.github.com\nSubject: Re: [krmaxwell/maltrieve] files aren't downloaded (#182)\nI use another branch:https://github.com/HarryR/maltrievehttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_HarryR_maltrieve&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=hnR4CUG_5RW7St8kny3Zj2jYyESlnu1fnxyBNkp7e_w&s=ImMWXvy9JguyGyD18hgz8h_EksXC54OyxhexyLaAmVc&e=. Now it works. I believe that you can success too.\n\u2014\nYou are receiving this because you authored the thread.\nReply to this email directly, view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_krmaxwell_maltrieve_issues_182-23issuecomment-2D284976575&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=hnR4CUG_5RW7St8kny3Zj2jYyESlnu1fnxyBNkp7e_w&s=06gLrt0YoyxjvFtkm4a7GAvquZxAmJ7e6NTS2c3pEmc&e=, or mute the threadhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYWdcmZoQZP1fBLF6IFcFh5qZLgSybn7ks5rjmSngaJpZM4L3jQB&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=hnR4CUG_5RW7St8kny3Zj2jYyESlnu1fnxyBNkp7e_w&s=7jmQV-TS7HXIQUgqqzHYvJ4krDZGvRk2JCBgST_Vbdk&e=.\n. I tried the other branch as well. The script runs but files aren\u2019t downloaded.\nFrom: panw-ren [mailto:notifications@github.com]\nSent: Monday, March 13, 2017 7:16 PM\nTo: krmaxwell/maltrieve maltrieve@noreply.github.com\nCc: Lindsay Hunt lhunt@paloaltonetworks.com; Author author@noreply.github.com\nSubject: Re: [krmaxwell/maltrieve] files aren't downloaded (#182)\nutilized the other branch as mentioned by hi-T0day but still no luck\nuser1@ubuntu-template:/maltrieve-0.7$user1@ubuntu-template: sudo ./maltrieve.py -d /home/user1/malware\nProcessing source URLs\nCompleted source processing\nDownloading samples, check log for details\nCompleted downloads\nuser1@ubuntu-template:/maltrieve-0.7$ cd /home/user1/malware/\nuser1@ubuntu-template:/malware$ ls\nuser1@ubuntu-template:/malware$\nhashesh.json/urls.json files are empty\n2017-03-13 16:13:32 140601425241856 Loaded urls from urls.json\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): support.clean-mx.de\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): www.malwaredomainlist.comhttps://urldefense.proofpoint.com/v2/url?u=http-3A__www.malwaredomainlist.com&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=R6DJP1xGammKLKO9gUDRnpLt92tJg5J4MwJCBancmS4&e=\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): vxvault.siri-urz.net\n2017-03-13 16:13:32 140601425241856 Starting new HTTPS connection (1): zeustracker.abuse.ch\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): urlquery.net\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): malwareurls.joxeankoret.com\n2017-03-13 16:13:32 140601425241856 Starting new HTTP connection (1): malc0de.com\n2017-03-13 16:13:32 140601425241856 http://www.malwaredomainlist.com:80https://urldefense.proofpoint.com/v2/url?u=http-3A__www.malwaredomainlist.com-3A80&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=UNzYjo7iIXamatlKLkZB8f2nTD4In38pUyJAQ8vfU6Y&e= \"GET /hostslist/mdl.xml HTTP/1.1\" 200 5735\n2017-03-13 16:13:33 140601425241856 https://zeustracker.abuse.ch:443https://urldefense.proofpoint.com/v2/url?u=https-3A__zeustracker.abuse.ch-3A443&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=nZhvJKTpPB2G48o2eYf9q4Vbl4Ghv5gqeVemvr4q_c0&e= \"GET /monitor.php?urlfeed=binaries HTTP/1.1\" 200 3882\n2017-03-13 16:13:33 140601425241856 http://malwareurls.joxeankoret.com:80https://urldefense.proofpoint.com/v2/url?u=http-3A__malwareurls.joxeankoret.com-3A80&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=CpGGDNuwiFTAU0uPo_OTyTrI6Fd5Pqwz9wK3oALFLLs&e= \"GET /normal.txt HTTP/1.1\" 200 11192\n2017-03-13 16:13:33 140601425241856 http://malc0de.com:80https://urldefense.proofpoint.com/v2/url?u=http-3A__malc0de.com-3A80&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=RPMsHT5AlMw5Zv2-bQwHRAKahuxjWm4X878Ugw6zQv8&e= \"GET /rss/ HTTP/1.1\" 200 None\n2017-03-13 16:13:33 140601425241856 http://urlquery.net:80https://urldefense.proofpoint.com/v2/url?u=http-3A__urlquery.net-3A80&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=WVKP32K7dT1Ld_Vr7mZGf9pu0_v7FCF1NDroJIZdwq4&e= \"GET / HTTP/1.1\" 200 4703\n2017-03-13 16:13:34 140601425241856 http://support.clean-mx.de:80https://urldefense.proofpoint.com/v2/url?u=http-3A__support.clean-2Dmx.de-3A80&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=j8aswoXreIR-aUyVOA-Db0HHo9wSJsBcjOH6C1BRSrM&e= \"GET /clean-mx/rss?scope=viruses&limit=0%2C64 HTTP/1.1\" 200 918\n2017-03-13 16:13:34 140601425241856 Dumping past URLs to urls.json\n2017-03-13 16:13:34 140601425241856 Dumping hashes to hashes.json\nuser1@ubuntu-template:/maltrieve-0.7$user1@ubuntu-template: more hashes.json\n[]\nuser1@ubuntu-template:/maltrieve-0.7$ more urls.json\n[]\n\u2014\nYou are receiving this because you authored the thread.\nReply to this email directly, view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_krmaxwell_maltrieve_issues_182-23issuecomment-2D286273343&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=ts5kOZDstSM7rgUsZXgEmooxocsWLuiq-bnXCCq5wk8&e=, or mute the threadhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYWdcnpTjnA9RPwMBgWF8ZMpoYxxpkYjks5rlc5MgaJpZM4L3jQB&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=F3HbLa-PYZ_cfGJw-BWkR8CsJX-ZYnlKAn5rGrHLKdo&m=36Z9msaMR4YTLtNr3Vl3XPHICnkpveWAe7rX5Q2Bc8o&s=AVablx8BNE0AZU0iUgT54rmnkCf5XFo4ispNrD9gfyM&e=.\n. ",
    "hi-T0day": "Add sudo before 'python maltrieve.py'  or change python to python3\nGood Luck!. Sorry, I gave you an wrong answer just now. But I got it now. \nYou can change in \"maltrieve.py\"\ndef process_urlquery(response):\n    soup = BeautifulSoup(response)\n    urls = set()\n    for t in soup.find_all(\"table\", class_=\"test\"):\n        for a in t.find_all(\"a\"):\n            urls.add('http://' + re.sub('&', '&', a.text))\n    return urls\nto:\ndef process_urlquery(response):\n    soup = BeautifulSoup(response, \"html.parser\")\n    urls = set()\n    for t in soup.find_all(\"table\", class_=\"test\"):\n        for a in t.find_all(\"a\"):\n            urls.add('http://' + re.sub('&', '&', a.text))\n    return urls. I use another branch:https://github.com/HarryR/maltrieve. Now it works. I believe that you can success too.. IF you add \"#\" before line8,9 in file \"maltrieve.cfg\" can maltrieve work?. ",
    "rkalugdan": "upon review, they were already commented out.\n[Maltrieve]\ndumpdir = archive\nlogfile = maltrieve.log\nlogheaders = true\nUser-Agent = Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)\nviper = http://127.0.0.1:8080\ncuckoo = http://127.0.0.1:8090\nvxcage = http://127.0.0.1:8080\ncrits = https://127.0.0.1\ncrits_user = maltrieve\ncrits_key = \ncrits_source = maltrieve\nFilter Lists are based on mime type NO SPACE BETWEEN ,\nblack_list = text/html,text/plain\nwhite_list = application/pdf,application/x-dosexec\n. bump. ",
    "getChester": "confirming that nothing is being downloaded.\n. ",
    "futex": "Same problem, nothing is downloaded.. ",
    "atefsaleh": "I realize questions are 2 years old but i have the same case of this issue, did anybody came up with a solution or cause ?\nThanks. Same here. "
}